server:
  port: 8080
  servlet:
    encoding:      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:    uri-encoding: UTF-8
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springboot_gyeongun?useUnicode=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: toor
  security:    user:      name: test
      password: 1234
    oauth2:      client:        registration:          google:
            client-id: 504145547452-6hitc44f1nlbm9g81e976s52kngq9rth.apps.googleusercontent.com
            client-secret: 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
            scope:            - email
            - profile
    
mybatis:  mapper-locations:  - /mappers/*.xml
    